#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sm8150-common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/init/wfdservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/wfdservice.rc \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/vendor.qti.ims.rcsservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/vendor.qti.ims.rcsservice.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/wfd-system-ext-privapp-permissions-qti.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/seccomp_policy/wfdservice.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/wfdservice.policy \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/seccomp_policy/wfdservice64.policy:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/seccomp_policy/wfdservice64.policy \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/sysconfig/qti_whitelist_system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_whitelist_system_ext.xml \
    vendor/xiaomi/sm8150-common/proprietary/system_ext/etc/wfdconfigsink.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/wfdconfigsink.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/hdr_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_config.cfg \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service-qti.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/init.mi_thermald.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.mi_thermald.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.qccvndhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qccvndhal@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/sdr_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/sdr_config.cfg \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base.policy \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext.policy \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/seccomp_policy/wfdhdcphalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdhdcphalservice.policy \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/seccomp_policy/wfdvndservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wfdvndservice.policy \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/seccomp_policy/wifidisplayhalservice.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/wifidisplayhalservice.policy \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/wfdconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wfdconfig.xml \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/11_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/11_version_update_ecc_table.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/xiaomi/sm8150-common/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    btaudio_offload_if \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vulkan.adreno \
    libC2D2 \
    libCB \
    libOpenCL \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libc2d30_bltlib \
    libcdsp_default_listener \
    libcdsprpc \
    libdiag \
    libfastcvdsp_stub \
    libfastcvopt \
    libgsl \
    libllvm-glnext \
    libllvm-qcom \
    libmdsprpc \
    libmmosal_vendor \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdsprpc \
    libsysmon_cdsp_skel \
    libthermalclient \
    libvppclient \
    libvpphcp \
    libvpphvx \
    libvpplibrary \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.vpp@1.3 \
    sound_trigger.primary.msmnile \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    libFileMux_proprietary \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadpcmdec \
    libaudcal \
    libcapiv2svacnn \
    libcapiv2vop \
    libfastcrc \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    liblistensoundmodel2 \
    libmmrtpdecoder_proprietary \
    libmmrtpencoder_proprietary \
    libmulawdec \
    libqcodec2 \
    libqtigef \
    libsmwrapper \
    libwfdcodecv4l2_proprietary \
    libwfdcommonutils_proprietary \
    libwfdconfigutils_proprietary \
    libwfddisplayconfig_proprietary \
    libwfdhdcpcp \
    libwfdhdcpservice_proprietary \
    libwfdmminterface_proprietary \
    libwfdmmservice_proprietary \
    libwfdmmsrc_proprietary \
    libwfdmodulehdcpsession \
    libwfdrtsp_proprietary \
    libwfdsessionmodule \
    libwfdsourcesession_proprietary \
    libwfdsourcesm_proprietary \
    libwfduibcinterface_proprietary \
    libwfduibcsink_proprietary \
    libwfduibcsinkinterface_proprietary \
    libwfduibcsrc_proprietary \
    libwfduibcsrcinterface_proprietary \
    libwfdutils_proprietary \
    libasphere \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    vendor.qti.hardware.wifidisplaysession@1.0_vendor \
    vendor.qti.hardware.wifidisplaysessionl@1.0-halimpl \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0_vendor \
    com.qualcomm.qti.imscmservice@2.1_vendor \
    com.qualcomm.qti.imscmservice@2.2_vendor \
    com.qualcomm.qti.uceservice@2.0_vendor \
    com.qualcomm.qti.uceservice@2.1_vendor \
    com.qualcomm.qti.uceservice@2.2_vendor \
    com.qualcomm.qti.uceservice@2.3_vendor \
    deviceInfoServiceModule \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.qccvndhal@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libQSEEComAPI \
    libQTEEConnector_listener \
    libQTEEConnector_vendor \
    libSecureUILib \
    libStDrvInt \
    libbtnv \
    libcacertclient \
    libcdfw \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libconfigdb \
    libcpion \
    libdataitems \
    libdisp-aba \
    libdisplayqos \
    libdpmqmihal \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libgdtap \
    libgnss \
    libgps.utils \
    libhdr_tm \
    libhexagon_nn_stub \
    libhta \
    libhta_hexagon_runtime \
    libidl \
    libizat_client_api \
    libizat_core \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    libloc_api_v02 \
    libloc_core \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdmdetect \
    libminkdescriptor \
    libminksocket \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    liboemcrypto \
    libops \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libqcbor \
    libqcc_file_agent \
    libqcci_legacy \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqdi \
    libqdp \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqseed3 \
    libqsocket \
    libqtikeymaster4 \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    librilqmiservices \
    librpmb \
    libsdedrm \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsecureui \
    libsecureui_svcsock \
    libsoc_helper \
    libspcom \
    libspl \
    libssc_default_listener \
    libssd \
    libsystem_health_mon \
    libtime_genoff \
    libtinyxml \
    libtinyxml2_1 \
    libtrustedapploader \
    libtzdrmgenprov \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    libwvdrmengine \
    qcrilHalMarshal \
    qcril_hal_client \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    unnhal-acc-adreno \
    unnhal-acc-common \
    unnhal-acc-hta \
    unnhal-acc-hvx \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.constants@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.server@1.0_vendor \
    vendor.qti.hardware.data.connection@1.0_vendor \
    vendor.qti.hardware.data.connection@1.1_vendor \
    vendor.qti.hardware.data.dynamicdds@1.0_vendor \
    vendor.qti.hardware.data.iwlan@1.0_vendor \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0_vendor \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccvndhal@1.0-halimpl \
    vendor.qti.hardware.qccvndhal@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.lpa@1.2 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.qtiradio@2.6 \
    vendor.qti.hardware.radio.qtiradio@2.7 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.callcapability@1.0_vendor \
    vendor.qti.ims.callinfo@1.0_vendor \
    vendor.qti.ims.factory@1.0_vendor \
    vendor.qti.ims.factory@1.1_vendor \
    vendor.qti.ims.rcsconfig@1.0_vendor \
    vendor.qti.ims.rcsconfig@1.1_vendor \
    vendor.qti.ims.rcsconfig@2.0_vendor \
    vendor.qti.ims.rcsconfig@2.1_vendor \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    capi_v2_aptX_CLHDAD_Encoder \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.wifidisplayhal@1.0 \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    libwfdavenhancements \
    libwfdclient \
    libwfdcommonutils \
    libwfdconfigutils \
    libwfddisplayconfig \
    libwfdmminterface \
    libwfdmmsink \
    libwfdmmsrc_system \
    libwfdrtsp \
    libwfdservice \
    libwfdsinksm \
    libwfduibcinterface \
    libwfduibcsink \
    libwfduibcsinkinterface \
    libwfduibcsrc \
    libwfduibcsrcinterface \
    vendor.qti.hardware.wifidisplaysession@1.0 \
    com.qualcomm.qti.dpm.api@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libimscamera_jni \
    libimsmedia_jni \
    libwfdnative \
    vendor.qti.ImsRtpService-V1-ndk \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.configservice@1.0 \
    vendor.qti.ims.connection@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.factory@2.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.ims.rcssip@1.0 \
    vendor.qti.ims.rcsuce@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    vendor.qti.imsrtpservice@3.1 \
    CACertService \
    CneApp \
    IWlanService \
    TimeService \
    PowerOffAlarm \
    HotwordEnrollmentOKGoogleHEXAGON_WIDEBAND \
    HotwordEnrollmentXGoogleHEXAGON_WIDEBAND \
    DeviceInfo \
    ImsRcsService \
    QtiTelephonyService \
    WfdService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    WfdCommon \
    tcmclient \
    com.android.hotwordenrollment.common.util \
    com.qti.dpmframework \
    com.qualcomm.qti.imscmservice-V2.0-java \
    com.qualcomm.qti.imscmservice-V2.1-java \
    com.qualcomm.qti.imscmservice-V2.2-java \
    com.qualcomm.qti.uceservice-V2.0-java \
    com.qualcomm.qti.uceservice-V2.1-java \
    com.quicinc.cne.api-V1.1-java \
    com.quicinc.cne.constants-V1.0-java \
    com.quicinc.cne.constants-V2.0-java \
    com.quicinc.cne.constants-V2.1-java \
    dpmapi \
    qcrilhook \
    qti-telephony-common \
    vendor.qti.hardware.alarm-V1.0-java \
    vendor.qti.hardware.data.cne.internal.api-V1.0-java \
    vendor.qti.hardware.data.cne.internal.constants-V1.0-java \
    vendor.qti.hardware.data.connection-V1.0-java \
    vendor.qti.hardware.data.connection-V1.1-java \
    vendor.qti.hardware.data.dynamicdds-V1.0-java \
    vendor.qti.hardware.data.iwlan-V1.0-java \
    vendor.qti.hardware.data.qmi-V1.0-java \
    vendor.qti.ims.callcapability-V1.0-java \
    vendor.qti.ims.callinfo-V1.0-java \
    vendor.qti.ims.connection-V1.0-java \
    vendor.qti.ims.connectionaidlservice-V1-java \
    vendor.qti.ims.factory-V2.0-java \
    vendor.qti.ims.factory-V2.1-java \
    vendor.qti.ims.factory-V2.2-java \
    vendor.qti.ims.factoryaidlservice-V1-java \
    vendor.qti.ims.rcsconfig-V1.0-java \
    vendor.qti.ims.rcssip-V1.0-java \
    vendor.qti.ims.rcssip-V1.1-java \
    vendor.qti.ims.rcssip-V1.2-java \
    vendor.qti.ims.rcssipaidlservice-V1-java \
    vendor.qti.ims.rcsuce-V1.0-java \
    vendor.qti.ims.rcsuce-V1.1-java \
    vendor.qti.ims.rcsuce-V1.2-java \
    vendor.qti.ims.rcsuceaidlservice-V1-java \
    android.hardware.neuralnetworks@1.3-service-qti-hta.xml \
    android.hardware.neuralnetworks@1.3-service-qti.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnd \
    cnss-daemon \
    dpmQmiMgr \
    dspservice \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@4.1-service-qti \
    android.hardware.neuralnetworks@1.3-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qccvndhal@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.qti.media.c2@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loc_launcher \
    lowi-server \
    mi_thermald \
    msm_irqbalance \
    netmgrd \
    nv_mac \
    pm-proxy \
    pm-service \
    power_off_alarm \
    ppd \
    qseecomd \
    qti \
    rmt_storage \
    slim_daemon \
    tftp_server \
    thermal-engine \
    time_daemon \
    vppservice \
    wifidisplayhalservice \
    xtra-daemon \
    dpmd \
    wfdservice \
    wfdservice64

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so

ifeq ($(TARGET_HAS_FM),true)

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init.qti.fm.sh:$(TARGET_COPY_OUT_VENDOR)/etc/init.qti.fm.sh \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/init.qti.fm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.fm.rc

PRODUCT_PACKAGES += \
    vendor.qti.hardware.fm@1.0-impl \
    fm_helium \
    libfm-hci \
    vendor.qti.hardware.fm@1.0 \
    fm_qsoc_patches

endif

ifneq ($(TARGET_IS_TABLET),true)

PRODUCT_PACKAGES += \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.gnss@4.0-service

endif

ifneq ($(TARGET_NOT_IN_CHINA),true)

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/xiaomi/sm8150-common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.mlipay@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.mlipay@1.1-service.rc

PRODUCT_PACKAGES += \
    vendor.qti.hardware.soter@1.0-impl \
    libmlipay \
    libmlipay@1.1 \
    vendor.qti.hardware.soter@1.0 \
    manifest_vendor.xiaomi.hardware.mlipay.xml \
    vendor.qti.hardware.soter@1.0-service \
    mlipayd@1.1

endif
